language: java

dist:
  - precise
  - trusty
  - osx

install:
  - git clone https://github.com/gonzalezsieira/spatial-utils
  - cd spatial-utils
  - mvn install
  - cd ..

script: mvn install -B -DreleaseType=Release -Djdk="$JAVA_HOME"